name: Test TikTok Video

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: "Public image URL"
        required: true
      audio_url:
        description: "Public audio URL"
        required: true
      filename:
        description: "Output filename"
        required: false
        default: "video.mp4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg curl

      - name: Set variables
        id: vars
        run: |
          IMAGE="${{ github.event.inputs.image_url }}"
          AUDIO="${{ github.event.inputs.audio_url }}"
          OUTNAME="${{ github.event.inputs.filename }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "AUDIO=$AUDIO" >> $GITHUB_ENV
          echo "OUTNAME=$OUTNAME" >> $GITHUB_ENV

      - name: Download image and audio
        run: |
          curl -fSL "$IMAGE" -o image
          curl -fSL "$AUDIO" -o audio

      - name: Build video with ffmpeg
        run: |
          ffmpeg -y -loop 1 -i image -i audio \
            -c:v libx264 -tune stillimage -r 30 -pix_fmt yuv420p \
            -c:a aac -b:a 192k \
            -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2" \
            -shortest "$OUTNAME"

      - name: List output
        run: ls -lh
