name: Make TikTok Video

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: "Public image URL"
        required: true
      audio_url:
        description: "Public audio URL"
        required: true
      filename:
        description: "Output filename (optional)"
        required: false
        default: "video.mp4"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow Dispatch works!"
